### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by SignalFlagZ** [Vetchems/sd-civitai-browser#12]
I am glad to see progress. Could you please add the license first?

**Comment by thetrebor** [comment]
What license do we want?  Apache 2 or copy A1111?

**Comment by SignalFlagZ** [comment]
A1111 has AGPL-3.0 license. Does this copyleft even apply to extensions? Does it have to be the AGPL3.0? Or can it be something else?

**Comment by thetrebor** [comment]
personally as a contributor i don’t care what anyone does with the code.
 what’s the default: “whatevs”  license?  unless vetchems has a strong
opinion we should probably just pick the one that’s easiest and loosest.

**Comment by SignalFlagZ** [comment]
I don't know the licensing laws, but AGPL 3.0 seems safe. We can also publish modifications of the code. This is just my opinion.  Wait for other opinions and please ask vetchems .

**Comment by thetrebor** [comment]
This has sat for a bit.
I’ll apply the MIT license or something similar if nobody cares:
https://choosealicense.com/licenses/mit/

Ill do it this weekend unless someone has objections.

**Comment by Vetchems** [comment]
I have no idea what license means what, i'd rather its not resold, but other than that i'm good with whichever. Inclusion of a link to the original project with any modifications would be nice.

**Comment by SignalFlagZ** [comment]
Thanks for the reply.
I agree that it is difficult to understand existing licenses. 
Our problem is that GitHub's default license does not allow us to publish even bug fixes in the code.  But we need permission to publish changes to the code.
If you have difficulty to choose an existing license, it would help us if you write in your ReadMe what you allow and what you don't allow.

**Comment by thetrebor** [comment]
Even easier, go here and answer their questions and it will tell you which
one to cut and paste.
Easy peasy simple:  https://choosealicense.com

**Comment by Vetchems** [comment]
Added AGPL3

**Comment by SignalFlagZ** [comment]
Thank you so much!
