### ISSUE TITLE
Not showing preview anymore

### ISSUE THREAD

**Issue by Tobe2d** [Vetchems/sd-civitai-browser#2]
It was working very well but for the last few days it stop showing preview of the models when selecting the model.

It works only if the model has multiple versions and select one of the versions from the drop down and go back to the 1st one on the list.

How to fix this? is it something on my side or is it a bug?

**Comment by rustyorb** [comment]
I'm having the same issue, in different colabs, some have this extension pre-installed some I've added. No matter, there is no preview and rarely get anything to download if ever Was working until about 1 or 2 days ago.

**Comment by gmorks** [comment]
I'm suspecting gradio update

**Comment by konservat0r** [comment]
I agree, it was good to use it, now it does not show preview

**Comment by Mattssn** [comment]
Unfortunately same, I just discovered this yesterday and was super stoked only for it to not work today :(

**Comment by thetrebor** [comment]
this should be fixed with the latest PR

**Comment by gmorks** [comment]
> this should be fixed with the latest PR

you are the hero this repo needed :D
