### ISSUE TITLE
Problem with update and load the info

### ISSUE THREAD

**Issue by wilzamguerrero** [Vetchems/sd-civitai-browser#6]
Hi thanks for this amazing tool, and thanks for share and help, well all works good but if the model only have one option for select is the problem and don't load the info for download I share some screens about this.

Look in this picture that the model have many options is perfect you can choose and download 
![image](https://user-images.githubusercontent.com/110712636/216894247-a89b500b-da14-4bfd-ae19-293147d68456.png)

But in this option when the model only have one option don't load the info for download
![image](https://user-images.githubusercontent.com/110712636/216894454-e65150bb-2331-403c-ab55-d20477f74d75.png)

and sometimes load the info but not the download url for can download with the button 
![image](https://user-images.githubusercontent.com/110712636/216895633-b22f5289-7ef0-41ab-8340-17aefc267c7c.png)

**Comment by elBlacksmith** [comment]
> Hi thanks for this amazing tool, and thanks for share and help, well all works good but if the model only have one option for select is the problem and don't load the info for download I share some screens about this.
> 
> Look in this picture that the model have many options is perfect you can choose and download ![image](https://user-images.githubusercontent.com/110712636/216894247-a89b500b-da14-4bfd-ae19-293147d68456.png)
> 
> But in this option when the model only have one option don't load the info for download ![image](https://user-images.githubusercontent.com/110712636/216894454-e65150bb-2331-403c-ab55-d20477f74d75.png)
> 
> and sometimes load the info but not the download url for can download with the button ![image](https://user-images.githubusercontent.com/110712636/216895633-b22f5289-7ef0-41ab-8340-17aefc267c7c.png)

Try this fork: https://github.com/axsddlr/sd-civitai-browser

**Comment by etherealxx** [comment]
@elBlacksmith the fork owner disabled issue tab, but from my experience using it in colab,
- Save image made this error
```
Save Images Clicked
http://imagecache.civitai.com/xG1nkqKTMzGDvpLrqFT7WA/2bbd3f97-9a01-4944-a686-cc0fbebbed00/width%3D450 elysiumKuroAnime_v1_0.png
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/gradio/routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.8/dist-packages/gradio/blocks.py", line 1015, in process_api
    result = await self.call_function(
  File "/usr/local/lib/python3.8/dist-packages/gradio/blocks.py", line 833, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.8/dist-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.8/dist-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.8/dist-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/content/stable-diffusion-webui/extensions/sd-civitai-browser/scripts/civitai-api.py", line 360, in save_image_files
    with open(os.path.join(model_folder, filename), 'wb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'models\\Stable-diffusion/Elysium_Kuro_Anime/elysiumKuroAnime_v1_0.png'
```
other than that, downloading model works.
